version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"

  - package-ecosystem: nuget
    directory: /tools
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      tooling:
        patterns:
          - "*"
