using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Company.AI.Tooling.Loading;

namespace Company.AI.Tooling.Vendoring;

/// <summary>
/// The <c>.vendored.json</c> marker written beside a vendored skill. It records where the content
/// came from and a hash of what was written, so drift can be detected without network access.
/// </summary>
internal sealed record VendorManifest(
    string Name,
    string Repository,
    string Path,
    string Commit,
    string ContentHash)
{
    public JsonObject ToJson() => new()
    {
        ["_comment"] = "Generated by 'vendor'. Do not edit; change external/sources.json instead.",
        ["name"] = Name,
        ["repository"] = Repository,
        ["path"] = Path,
        ["commit"] = Commit,
        ["contentHash"] = ContentHash
    };

    public static VendorManifest? FromJson(JsonNode? node)
    {
        if (node is not JsonObject obj)
        {
            return null;
        }

        var name = obj["name"]?.GetValue<string>();
        var repository = obj["repository"]?.GetValue<string>();
        var path = obj["path"]?.GetValue<string>();
        var commit = obj["commit"]?.GetValue<string>();
        var hash = obj["contentHash"]?.GetValue<string>();

        if (name is null || repository is null || path is null || commit is null || hash is null)
        {
            return null;
        }

        return new VendorManifest(name, repository, path, commit, hash);
    }

    /// <summary>
    /// Hashes a vendored directory: every file's repo-relative path and bytes, in a stable order.
    /// The marker file is excluded, since it carries the hash it would otherwise change.
    /// </summary>
    public static string HashDirectory(string directory)
    {
        using var sha = SHA256.Create();

        var files = Directory
            .EnumerateFiles(directory, "*", SearchOption.AllDirectories)
            .Where(f => System.IO.Path.GetFileName(f) != ExternalSources.MarkerFileName)
            .Select(f => (Relative: Io.PathUtils.Relative(directory, f), Full: f))
            .OrderBy(f => f.Relative, StringComparer.Ordinal)
            .ToList();

        foreach (var file in files)
        {
            var nameBytes = Encoding.UTF8.GetBytes(file.Relative + "\n");
            sha.TransformBlock(nameBytes, 0, nameBytes.Length, null, 0);

            var content = File.ReadAllBytes(file.Full);
            sha.TransformBlock(content, 0, content.Length, null, 0);
        }

        sha.TransformFinalBlock([], 0, 0);

        return Convert.ToHexStringLower(sha.Hash!);
    }
}
